services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: gunicorn --bind 0.0.0.0:5000 app:app
    
    image: flasktemplate-api
    container_name: flaskapi
    restart: always
    
    

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: flasktemplate-client
    container_name: flaskclient
    restart: always
    ports:
      - "80:80"
      
      
      
      
    

    
      